// <auto-generated />
namespace Food_Truck.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class descriptionforfooditem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(descriptionforfooditem));
        
        string IMigrationMetadata.Id
        {
            get { return "201611101756162_description for food item"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
