// <auto-generated />
namespace Food_Truck.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class food_Itemreplacedmenu_item : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(food_Itemreplacedmenu_item));
        
        string IMigrationMetadata.Id
        {
            get { return "201611091610511_food_Item replaced menu_item"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
