// <auto-generated />
namespace Food_Truck.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedforeignkeytotruckonemployee : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedforeignkeytotruckonemployee));
        
        string IMigrationMetadata.Id
        {
            get { return "201611101530027_added foreign key to truck on employee"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
